### ISSUE TITLE
When will this code be available?

### ISSUE THREAD

**Issue by ofgulban** [dchaimow/vdfs#1]
Dear @dchaimow ,

Hope all is well with you. Stumbling upon this repository, I became very curious to see your new method and check how does it compare to the triangular mesh based and quad-grid based methods implemented in e.g. Brainvoyager (compute depths in triangular mesh space and transform it to voxel space, [see ref and figure below]). Might be a good way to handle lower res data (e.g. 0.8 mm iso). I couldn't see the code yet, when will it be available?

- Kemper, V. G., De Martino, F., Emmerling, T. C., Yacoub, E., & Goebel, R. (2018). High resolution data analysis strategies for mesoscale human functional MRI at 7 and 9.4T. NeuroImage, 164, 48–58. https://doi.org/10.1016/j.neuroimage.2017.03.058

![Screenshot from 2022-05-27 11-51-00](https://user-images.githubusercontent.com/4668327/170676235-099c0fb0-ffe7-4b6f-bf77-7b1c25b61097.png)

**Comment by dchaimow** [comment]
Hi Faruk,

I am about to make the repository ready for my OHBM poster. So far the code lives in my general analysis repository under: https://github.com/dchaimow/fmri-analysis/blob/main/library/voxeldepths_from_surfaces.py .

I am very curious to hear what you think!

**Comment by ofgulban** [comment]
Cool, looking forward for the poster. Hopefully see you at Glasgow (if I can get a visa on time :D ).

Looking at the code, it seems like you are dependent on Freesurfer triangular meshes. Do you perform triangle subdivision to increase the mesh resolution (e.g. like Kay2019 [ref below]) or does your method makes this step unnecesary?

- Kay, K., Jamison, K. W., Vizioli, L., Zhang, R., Margalit, E., & Ugurbil, K. (2019). A critical assessment of data quality and venous effects in sub-millimeter fMRI. NeuroImage, 189(February), 847–869. https://doi.org/10.1016/j.neuroimage.2019.02.006

![Screenshot from 2022-05-27 12-16-57](https://user-images.githubusercontent.com/4668327/170680894-2d1a9ea8-d4e3-47bd-9a13-f01bf7ede3f6.png)

**Comment by ofgulban** [comment]
Hmm, looking at the code a bit more, I think this method will work well for lower res data (e.g. ~0.8 mm iso. and >~0.5 mm iso.), but since you have Freesurfer dependency,  it will inherit all the disadvantages when you have data that does not fit well to Freesurfer defaults (e.g. partial coverage, very high res data, different contrasts etc.). In other words, you are as good as your mesh quality, and your meshes are as good as your segmentation quality. Which is the real bottleneck for very high res and partial coverage data. 

However, this being said, I like the idea of ending up in the voxel grid. So, I like the transformation the mesh data back to voxel grid. As far as I know Brainvoyager and CBS-Tools have this capability and people regularly use them. Though there are core issues if you are using the meshes to define "columns" (I see that you have column related parts in your code), maybe sth to discuss anther time. I would be most curious to hear how (or if) you handle partial coverage data. Also, I think your code can be developed further to process other mesh formats. Maybe something to look into for a more generalised solution.

**Comment by dchaimow** [comment]
Hi Faruk,

I added the code and a README to the repository.

Thanks for your valuable comments. Hopefully we can discuss this further in Glasgow.

Just very briefly: 

Yes, everything depends on how good the surface. I simply thought, if one wants to rely on surfaces, it would be good to have a way of directly generating depths in function space (FYI: I am combining this approach with first transforming the freesurfer surfaces using a non-linear ANTS transform (from freesurfer -> EPI registration) to EPI voxel space.

Yes, the columns are the freesurfer columns or face pairs. May not be the best way to define columns, but it is a byproduct of the algorithm and it tells you which face pair each voxel center belongs to.

Partial coverage would be a problem if it is partial coverage of the anatomy. If we are talking about partial coverage of EPI, then this method may even work better at the boundaries as it only cares about surfaces and individual voxel coordinates.

Increasing the density of the should probably not make any difference if the geometry of the surface isn't changed, but I may be wrong.

Best,
Denis
